name: dotnet CI

on:
  push:
    paths:
      - 'GameStore/GameStoreAPI/**'
  pull_request:
    paths:
      - 'GameStore/GameStoreAPI/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Verify installed SDKs
        run: dotnet --list-sdks  # 👈 Shows installed versions

      - name: Restore dependencies
        run: dotnet restore GameStore/GameStoreAPI/GameStoreAPI.csproj

      - name: Build project
        run: dotnet build GameStore/GameStoreAPI/GameStoreAPI.csproj --no-restore --configuration Release

      - name: Run tests
        run: dotnet test GameStore/GameStoreAPI/GameStoreAPI.csproj --no-build --verbosity normal
