name: Frontend CI

on:
  push:
    paths:
      - 'game-store-frontend/**'
  pull_request:
    paths:
      - 'game-store-frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - run: cd game-store-frontend && npm ci
      - run: cd game-store-frontend && npm run build
      - run: cd game-store-frontend && npm test
