name: Frontend CI

on:
  push:
    paths:
      - 'game-store-frontend/**'
  pull_request:
    paths:
      - 'game-store-frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: cd game-store-frontend && npm ci

    - name: Build
      run: cd game-store-frontend && npm run build

    - name: Run tests
      run: cd game-store-frontend && npm test
